### ISSUE TITLE
potential encoding error for CIDs 13679 and 13329

### ISSUE THREAD

**Issue by DarrenHoffman** [adobe-type-tools/Adobe-Japan1#1]
CID 13329 appears to be the Kyūjitai version of U+69EA and CID 13679 appears to be the Shinjitai version of the same code point U+69EA.
U+2F8EA is the same character in the CJK Compatibility Ideographs block as I understand it.
My (perhaps mistaken) understanding is that old form versions of Kanji map to the compatibility block, and new forms to the regular block(s) (I'm still a Unicode neophyte) thus:
CID 13679 should map to U+69EA and CID 13329 should map to U+2F8EA.
But the relevant cmaps and the cid2code.txt file seem to have this backwards.
Thanks.

**Comment by wtn** [comment]
The [entry](https://www.kanjipedia.jp/kanji/0000864600) in 漢字ペディア clarifies the situation.

U+6982 → 新字体
U+69EA → 旧字体
U+2F8EA → 旧字体

Only some kyūjitai use compatibility characters, see [Wikipedia](https://en.wikipedia.org/wiki/List_of_jōyō_kanji).

**Comment by kenlunde** [comment]
There is no bug.

The U+69EA to CID+13679 mapping in the long-deprecated UniJIS-UCS-H CMap resource was corrected to CID+13329 when the UTF-{8,16,32} CMap resources were deployed, which were aligned with the JIS X 0213 standard. The representative glyph in JIS X 0213 matches that of CID+13329. The corresponding representative glyph in the "J" column of the Unicode code charts also reflects a glyph that matches CID+13329.
![uni69EA](https://user-images.githubusercontent.com/3988788/62645227-9f952100-b900-11e9-9432-eda6e6906443.jpg)

**Comment by DarrenHoffman** [comment]
ok, thanks for the clarification. I'm not very familiar with CJK but ran into a seeming discrepancy between a ToUnicode Cmap embedded in a PDF and the correct encoding. (The embedded ToUnicode CMap was perhaps based on the old UCS CMap)

**Comment by kenlunde** [comment]
Having just inspected the Adobe-Japan1-UCS2 "ToUnicode" mapping file [here](https://github.com/adobe-type-tools/mapping-resources-pdf/), I agree with your assessment that the embedded ToUnicode mapping table is likely based on the UniJIS-UCS2-H CMap resource.

**Comment by DarrenHoffman** [comment]
is there a good forum you'd recommend where I can ask more questions about any CJK/Unicode details that confuse me in the future? 
One last question, so is it probably true that Adobe-Japan1 CID 13679 would not be commonly found in typical Japanese texts? (the pdf I'm dealing with is an OCR'd image of some tables containing both Japanese text and molecular diagrams, the occurrence of CID 13679 in this document appears to be due to the OCR agent confusing some molecular labels for Japanese and making a bad match)
My current understanding is that U+6982 is the modern version of U+69EA (at least in Japanese) and that maybe the only reason U+2F8EA exists is because U+69EA is rendered a bit differently in Japanese than say Chinese. I know this is probably at best a crude understanding, so thanks for bearing with me. And sorry for reporting a bug that wasn't a bug, but man I was confused.

**Comment by kenlunde** [comment]
Twitter works, and unfortunately your tweets came in while I was in a team meeting. By the time it had ended, you had posted this issue. You can also use my email address, which is simply my family name "at" adobe.com.

About these characters, the IRG source references are revealing:

```
U+6982 概
  kIRG_GSource	G0-3845
  kIRG_HSource	HB1-B7A7
  kIRG_JSource	J0-3335 ← JIS X 0208 Level 1
  kIRG_TSource	T1-644D
U+69EA 槪
  kIRG_GSource	GE-2E66
  kIRG_JSource	J3-7624 ← JIS X 0213 Level 3
  kIRG_KPSource	KP0-D3A7
  kIRG_KSource	K0-4B48
  kIRG_TSource	T3-4C60
U+2F8EA 槪 CJK COMPATIBILITY IDEOGRAPH-2F8EA
  kIRG_TSource	T7-2372
```

U+6982 概 has a Japanese source (JIS X 0208 Level 1), as does U+69EA 槪 (JIS X 0213 Level 3), but U+2F8EA 槪 does not. Its shape happens to be the same as CID+13679, hence the mapping. The preferred way to express CID+13679 is via its Adobe-Japan1 IVS, which is <U+69EA, U+E0101>.
