### ISSUE TITLE
Previous Releases

### ISSUE THREAD

**Issue by waji-io** [adobe-type-tools/Adobe-Japan1#2]
Hi,

Are there any plans to also release older versions (PDFs) here, like Adobe-Japan1-0.

Cheers
Joern

**Comment by hatchzo** [comment]
You can find 5078.Adobe-Japan1-6 Technical Note:

https://www.adobe.com/content/dam/acom/en/devnet/font/pdfs/5078.Adobe-Japan1-6.pdf

Adobe-Japan1-7 documents cover all Adobe-Japan1 collection. We do not have any plans to release old documents.
